### ISSUE TITLE
DS 설명파일 form 정리 

### ISSUE THREAD

**Issue by SoYoung210** [SoYoung210/acmicpc_note#3]
기본적으로 들어가야 하는 내용을 작성해서 **백준 1697번 문제** 를 기준으로 적어보았습니다. 
> [acmicpc_note/DS_TeamProject_C/SY_kkao+boj/boj/B_1697.javad](url)

제가 작성한 내용은, 

- 문제접근

-  기본적 알고리즘

- 변형되어야 하는 점

- 변형 코드

- 유의할 점

등으로 적어보았습니다. 
추가되어야 하는 내용은 댓글로 달아주세요.

**Comment by KimHunJin** [comment]
[404 not found error] 폴더의 변경으로 인해 링크가 404를 뱉어주네요.

**Comment by SoYoung210** [comment]
@KimHunJin 감사합니다. 링크 수정했습니다.
